spring:
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        datasource:
            driverClassName: org.h2.Driver
            url: jdbc:h2:~/test
            username: sa
            password: